# NumPy

[NumPy](https://numpy.org/) (Numerical Python) es la librería fundamental de python para realizar tareas de computación científica. Entre otros, contiene:

* Variables de tipo array n-dimensionales.
* Funciones matemáticas de álgebra lineal, estadística, cálculo, etc.
* Soporte para vectorizar las operaciones anteriores sobre los arrays de forma eficiente.

Empezamos cargando la librería, usaremos el alias `np`

In [1]:
import numpy as np

## Arrays

Los objetos principales de NumPy es el array multidimensional homogéneo. Un array es una tabla de elementos (normalmente números), todos del mismo tipo (homogéneo), indexados por una tupla de enteros positivos. En NumPy a las dimensiones se las llama ejes (axes). El número de ejes es el rango (rank).

Por ejemplo, las coordenadas del punto `[1, 2, 0]` en el espacio es un array de rango 1, pues solo tiene un eje. Ese eje tiene longitud (length) 3. 
En el ejemplo siguiente, el array tiene rango 2 (tiene dos ejes, es una matriz). El primero tiene longitud 2, mientras que el segundo tiene longitud 3.

`[[ 1., 0., 0.],
 [ 0., 1., 2.]]`
 
El elemento en la posición `(1, 2)` es el 2.

## Creación de arrays

Lo más simple es utilizar `array` que toma una lista de python y crea el array, deduciendo el tipo automáticamente:

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)

In [3]:
x

array([1, 2, 3])

El array tienen algunos atributos que guardan información del objeto:

* `dtype`: el tipo de los elementos del array. Suele ser int o float, acompañado de la precisión
* `shape`: las dimensiones del array

In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(3,)

In [6]:
x = np.array([1, 2, 3.5])
x

array([1. , 2. , 3.5])

In [7]:
x.dtype

dtype('float64')

<br>
Para crear arrays multidimensionales, podemos pasarle listas de listas de ... a `array`:

In [8]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
m.shape

(2, 3)

Para acceder a las filas y columnas:

In [10]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(str(X[0][0])+" "+str(X[0][1])+" "+str(X[0][2])) 
print(str(X[1][0])+" "+str(X[1][1])+" "+str(X[1][2])) 
print(str(X[2][0])+" "+str(X[2][1])+" "+str(X[2][2])) 

1 2 3
4 5 6
7 8 9


<br>
También podemos crear arrays utilizando constructores con comportamientos predefinidos, sin tener que explicitarle todos los elementos

`arange` devuelve valores equiespaciados en un intervalo dado

In [12]:
x = np.arange(0, 30, 2.3) # de 0 a 30 contando de 2.3 en 2.3
x

array([ 0. ,  2.3,  4.6,  6.9,  9.2, 11.5, 13.8, 16.1, 18.4, 20.7, 23. ,
       25.3, 27.6, 29.9])

<br>
`linspace` es similar, solo que en el último argumento se le especifica el número de puntos que queremos

In [13]:
x = np.linspace(0, 30, 9) # 9 números equiespaciados en [0, 30]
x

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  , 18.75, 22.5 , 26.25, 30.  ])

<br>
`zeros` y `ones` crean arrays de la forma especificada rellenos con 0s y 1s, respectivamente

In [14]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
3*np.ones([2,2,3])

array([[[3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.]]])

<br>
`eye` crea una matriz identidad de tamaño dado, y `diag` crea un array diagonal

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.diag([6,8,9])

array([[6, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

## Combinación de arrays

In [20]:
x = np.ones([2, 3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

<br>
`vstack` permite apilar arrays en serie verticalmente (añade filas).

In [21]:
np.vstack([x, 2*x])

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

<br>
`hstack` permite apilar arrays en serie horizontalmente (añade columnas).

In [22]:
np.hstack([x, 2*x, 3*x])

array([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.]])

## Operaciones sobre arrays

La función `reshape` permite cambiar las dimensiones de los arrays. Vemos en el ejemplo que empieza a rellenarlo a lo largo del último eje (en este caso, el de longitud 5):

In [23]:
x = np.arange(0, 15)
x = x.reshape([3,5])
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

<br>
Dado el array, podemos consultar o modificar cualquier elemento:

In [24]:
x[0,1] = 100*x[0,1]
x

array([[  0, 100,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [25]:
np.arange(0, 15).reshape([3,5], order='F') # Podemos especificar que los elementos se almacenen primero a lo largo
                                           # de la otra dimensión

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

<br>
Con el atributo `.T` podemos trasponer el array

In [26]:
x.T

array([[  0,   5,  10],
       [100,   6,  11],
       [  2,   7,  12],
       [  3,   8,  13],
       [  4,   9,  14]])

<br>
Observamos  que en el caso de trabajar con arrays de rango > 2, también se puede usar `.T`:

In [27]:
np.arange(0,24).reshape([2,3,4])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
np.arange(0,24).reshape([2,3,4]).T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

Usa `+`, `-`, `*`, `/` y `**` para realizar la suma, resta, producto, division y potencia elemento a elemento

In [29]:
np.arange(1,5) + np.arange(1,5)

array([2, 4, 6, 8])

In [30]:
np.arange(1,5) - np.arange(1,5)

array([0, 0, 0, 0])

In [31]:
np.arange(1,5) / np.arange(1,5)

array([1., 1., 1., 1.])

In [32]:
#(a1,a2) * (b1,b2) = (a1*b1,a2*b2)
np.arange(1,5) * np.arange(1,5)

array([ 1,  4,  9, 16])

In [33]:
#(a1,a2).dot((b1,b2)) = (a1*b1+a2*b2)
np.arange(1,5).dot(np.arange(1,5))

30

In [34]:
np.arange(1,5)**2

array([ 1,  4,  9, 16])

In [35]:
#modulo de un vector
print(np.linalg.norm(np.arange(1,5)))

5.477225575051661


`dot` realiza el producto escalar en el caso de vectores y el producto usual en el caso de matrices

In [36]:
M = np.arange(16).reshape(4,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
np.dot(M, np.eye(4))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [38]:
# El operador * es el producto elemento a elemento:
M * np.eye(4)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 15.]])

También podemos realizar el producto usual de matrices usando `@` en vez de `*`:

In [39]:
M @ np.eye(4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [40]:
x = np.array([[3, 2, 1], [4, 0, 6]])
x=np.ravel(x) #reshape(-1, order=order)
print(x)

[3 2 1 4 0 6]


In [41]:
X = x.astype('float32')
print(X)
X /= 6
print(X)

[3. 2. 1. 4. 0. 6.]
[0.5        0.33333334 0.16666667 0.6666667  0.         1.        ]


In [42]:
y = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])
np.ravel(y) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
y = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])
y_new = []
for i in range(len(y)):
    y_new.append(np.ravel(y[i]))
y_new = np.array(y_new)
print(y_new)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Funciones matemáticas

Numpy tiene varias funciones incluidas para hacer operaciones en `arrays`. Por ejemplo:

In [44]:
a = np.array([-4, -2, 1, 3, 5])

In [45]:
a.sum()

3

In [46]:
a.prod()

120

In [47]:
a.max()

5

In [48]:
a.min()

-4

In [49]:
#índice para el que se alcanza el máximo
a.argmax()

4

In [50]:
#índice para el que se alcanza el mínimo
a.argmin()

0

In [51]:
ages = [10,14,15,16,30,40,50,60]
P=50
x = np.percentile(ages, P)
print("un",P,"% de la gente tiene menos de",x) 

un 50 % de la gente tiene menos de 23.0


- __La mediana__ es el valor que ocupa la posición central. 
- __La moda__ es el valor que más se repite o, lo que es lo mismo, el que tiene la mayor frecuencia
- __La media__, es el promedio  
$$\mu = \frac{1}{N}\sum_{i=1}^{N} x_i$$
- __La desviación estandar__ es una medida que se utiliza para cuantificar la variación o la dispersión de un conjunto de datos numéricos  
$$\sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N} ( \mu  - x_i )^{2}} $$

In [52]:
a = np.array([0,0,1,1,8])

In [53]:
#mediana
np.median(a)

1.0

In [54]:
from scipy import stats #ojo no esta en numpy
stats.mode(a)

ModeResult(mode=array([0]), count=array([2]))

In [55]:
#media o promedio
s=""
for i in range(len(a)):
    if i > 0:
        s=s+"+"+str(a[i])
    else:
        s="("+str(a[i])
s=s+")/"+str(len(a))+" = "+str(a.mean())
print(s)    

(0+0+1+1+8)/5 = 2.0


In [56]:
#std: standard deviation (desviación estándar)
s=""
for i in range(len(a)):
    j="("+str(a.mean())+str("-")+str(a[i])+")²"
    if i > 0:
        s=s+"+"+j
    else:
        s="sqrt(("+j
s=s+")/"+str(len(a))+") = "+str(a.std())
print(s)   


sqrt(((2.0-0)²+(2.0-0)²+(2.0-1)²+(2.0-1)²+(2.0-8)²)/5) = 3.03315017762062


## Indexing/Slicing

Al igual que en las listas, `[]` permiten indexar arrays.

In [57]:
ll = np.arange(20)
print(ll)
ll[0], ll[4], ll[-1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(0, 4, 19)

Para hacer slicing, se pueden utilizar expresiones del tipo `start:stop:step`

In [58]:
ll[0:5:2]

array([0, 2, 4])

Para contar empezando por detrás, se pueden usar números negativos

In [59]:
ll[-4:]

array([16, 17, 18, 19])

Ahora vayamos al caso de arrays de más de una dimensión

In [60]:
h = np.arange(34)
h.resize((6, 6))
h

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33,  0,  0]])

Para hacer slicing se utilizar: `array[fila, columna]`

In [61]:
h[2, 2]

14

Usando : se seleccionan grupos de filas o columnas

In [62]:
h[1, 3:6]

array([ 9, 10, 11])

Así selecciona de la matriz `h`todas las filas hasta la 2 (sin incluír esta) y todas las columnas hasta la penúltima (sin incluír esta).

In [63]:
h[:2, :-2]

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

Así seleccionamos toda una fila

In [64]:
h[-1, :]

array([30, 31, 32, 33,  0,  0])

Así seleccionamos toda una columna

In [65]:
h[:, 0]

array([ 0,  6, 12, 18, 24, 30])

También podemos hacer indexing condicional. Así seleccionamos todos los elementos distintos de cero.

In [66]:
h[h != 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

## Operaciones sobre filas o columnas

Podemos realizar operaciones por filas o columnas usando la opción `axis`. En concreto, para sumar por filas y columnas hacemos:

In [67]:
p=np.arange(16).reshape(4,4)
print(p)
print("Suma por filas: ", p.sum(axis = 1))
print("Suma por columnas: ", p.sum(axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Suma por filas:  [ 6 22 38 54]
Suma por columnas:  [24 28 32 36]


En concreto, con la función `np.apply_along_axis(función, eje, array)` podemos aplicar cualquier función que definamos por filas o columnas.

In [68]:
def arggmax(x):
    return np.argmax(x)

print(np.apply_along_axis(sum,1, p))
print(np.apply_along_axis(arggmax,1, p))
print(p.argmax(axis = 1))

[ 6 22 38 54]
[3 3 3 3]
[3 3 3 3]


### Iterar sobre arrays

Sea la siguiente matriz

In [69]:
test = np.arange(12)
test.resize((4, 3))
test

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Iterar sobre filas:

In [70]:
for row in test:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


Iterar sobre índices

In [71]:
for i in range(len(test)):
    print(test[i])

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


Iterar por fila y columna:

In [72]:
for i in range(len(test)):
    for j in range(len(test[i])):
        print('test['+str(i)+']'+str(j)+'] = '+str(test[i][j]))

test[0]0] = 0
test[0]1] = 1
test[0]2] = 2
test[1]0] = 3
test[1]1] = 4
test[1]2] = 5
test[2]0] = 6
test[2]1] = 7
test[2]2] = 8
test[3]0] = 9
test[3]1] = 10
test[3]2] = 11


In [73]:
test2 = test**2
test2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

También podemos hacer una función de una matriz masandola a

### Save and load

In [74]:
np.save('array.npy', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('array.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
aw=np.array([[1, 2, 3], [4, 5, 6]])
bw=np.array([1, 2])

#guardarlos comprimidos
np.savez('array2.npz', aw=aw, bw=bw)
data = np.load('array2.npz')

ar=data['aw']
print(ar)

br=data['bw']
print(bw)

data.close()

[[1 2 3]
 [4 5 6]]
[1 2]


### Cadenas de Márkov

Las cadenas de Márkov es un tipo especial de proceso estocástico discreto en el que la probabilidad de que ocurra un evento depende solamente del evento inmediatamente anterior.

Imaginar la siguiente situación:

<img src="markov.gif"  width="400" >

Tendríamos la siguiente matriz de transición

In [76]:
M = np.array([[0.6,0.3,0.1],[0.3,0.5,0.2],[0.4,0.3,0.3]])
print(M)

[[0.6 0.3 0.1]
 [0.3 0.5 0.2]
 [0.4 0.3 0.3]]


In [77]:
#Pongamos el caso de una población 1000 habitantes que en un momento inicial compran las marcas siguiendo la siguiente distribución:
V=np.array([300,500,200])
#para estimar lo que sucederá en la siguiente compra tendremos que multiplica la matriz M por el vector V
V1=V.dot(M)
print(V1)

[410. 400. 190.]


In [78]:
#para seguir estimando, haremos lo mismo
V2=V1.dot(M)
print("V2 = ",V2)
V3=V2.dot(M)
print("V3 = ",V3)
V4=V3.dot(M)
print("V4 = ",V4)
V5=V4.dot(M)
print("V5 = ",V5)
V6=V5.dot(M)
print("V6 = ",V6)
V7=V6.dot(M)
print("V7 = ",V7)
V8=V7.dot(M)
print("V8 = ",V8)

V2 =  [442. 380. 178.]
V3 =  [450.4 376.  173.6]
V4 =  [452.48 375.2  172.32]
V5 =  [452.976 375.04  171.984]
V6 =  [453.0912 375.008  171.9008]
V7 =  [453.11744 375.0016  171.88096]
V8 =  [453.123328 375.00032  171.876352]


In [79]:
#Podíamos tener el mismo resultado utilizando las potencias de la matriz
print(" -- M --")
print(M)
print("")

M2=M.dot(M)
print(" -- M2 --")
print(M2)
print("")

M3=M2.dot(M)
print(" -- M3 --")
print(M3)
print("")

M4=M3.dot(M)
print(" -- M4 --")
print(M4)
print("")

M5=M4.dot(M)
print(" -- M5 --")
print(M5)
print("")

M6=M5.dot(M)
print(" -- M6 --")
print(M6)
print("")

print("El 6º salto: V*M6")
print("V6 = ",V.dot(M6))

 -- M --
[[0.6 0.3 0.1]
 [0.3 0.5 0.2]
 [0.4 0.3 0.3]]

 -- M2 --
[[0.49 0.36 0.15]
 [0.41 0.4  0.19]
 [0.45 0.36 0.19]]

 -- M3 --
[[0.462 0.372 0.166]
 [0.442 0.38  0.178]
 [0.454 0.372 0.174]]

 -- M4 --
[[0.4552 0.3744 0.1704]
 [0.4504 0.376  0.1736]
 [0.4536 0.3744 0.172 ]]

 -- M5 --
[[0.4536  0.37488 0.17152]
 [0.45248 0.3752  0.17232]
 [0.45328 0.37488 0.17184]]

 -- M6 --
[[0.453232 0.374976 0.171792]
 [0.452976 0.37504  0.171984]
 [0.453168 0.374976 0.171856]]

El 6º salto: V*M6
V6 =  [453.0912 375.008  171.9008]
