<b><font color='red'>Ejercicio 01</font></b>  

Selecciona las primera columna de la matriz `p` proporcionada, y guárdala en la variable `p1`. Sustituye los elementos de p1 que sean iguales a 0, por el valor $7$.

In [1]:
import numpy as np
p = np.array([[1,2,4],[0,0,0],[0,6,8]])
print(p)

p1 = p[:, 0]
result = np.where(p1 == 0, 7, p1)

print(result)

[[1 2 4]
 [0 0 0]
 [0 6 8]]
[1 7 7]


<hr>
<b><font color='red'>Ejercicio 02</font></b>  

Obtener una función que calcule la distancia forman dos vectores

$$
v=[v_1,v_2,v_3,...]
\newline
u=[u_1,u_2,u_3,...]
\newline
d=\sqrt{ (u_1-v_1)^2 + (u_2-v_2)^2 + (u_3-v_3)^2 + ... }
$$

In [2]:
def d(v, u):
    if(len(v) == len(u)):
        calculo = np.linalg.norm(v -u) 
    return calculo

v = np.array([1,-1])
u = np.array([0,1])

print(d(v,u)) # El resultado debería de ser 2.2360679775 

2.23606797749979


<hr>
<b><font color='red'>Ejercicio 03</font></b>  

Obtener una función que calcule el coseno del ángulo que forman dos vectores

$$ \cos \theta = \frac{\langle v, u \rangle}{||v|| ||u||} $$

donde $|| v ||$ es la norma del vector v, que se puede expresar como $\sqrt{\langle v, v \rangle} = \sqrt{ v_1^2 +  v_2^2 +  v_3^2 + ... }$ y el producto escalar $\langle v, u \rangle = v_1 u_1 + v_2 u_2 + ...$


In [3]:
def cos(v, u):
    dot = np.dot(v, u)
    v_norm = np.linalg.norm(v)
    u_norm = np.linalg.norm(u)

    coseno = dot / (v_norm * u_norm)
    return coseno

v = np.array([0,-1])
u = np.array([0,1])

print(cos(v,u))  # El resultado debería de ser -1.0

-1.0


<hr>
<b><font color='red'>Ejercicio 04</font></b>  

Vuelve hacer el ejercicio que hicimos en el cápitulo anterior, utilizando las funciones de numpy:

Crea una función que te devuelva la media y la desviación estándar de una lista ordenada.  
Pruébalo con lista = [4, 1, 11, 13, 2, 7]  
ayuda : https://es.wikipedia.org/wiki/Desviaci%C3%B3n_t%C3%ADpica

In [4]:
#hemos borrado las funciones, cambia el codígo siguiente

lista = [4, 1, 11, 13, 2, 7]
print(lista)

def media(lista):
    return np.mean(lista)

def DES(lista):
    return np.std(lista)

print(f"media = {(media(lista)):.2f} \u00B1 {(DES(lista)):.2f}")

[4, 1, 11, 13, 2, 7]
media = 6.33 ± 4.46


<hr>
<b><font color='red'>Ejercicio 05</font></b>  

Crear un array con 1 en el borde y  0 dentro

In [5]:
array_zeros = np.zeros((10, 10))

array_zeros[0, :] = 1
array_zeros[:, 0] = 1
array_zeros[-1, :] = 1
array_zeros[:, -1] = 1


print(array_zeros)
# la salida tiene que ser:
#array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


<hr>
<b><font color='red'>Ejercicio 06</font></b>  

Fíjate en el siguiente sistema de ecuaciones:
$$-x+y=1 \\ x+y=3$$

Escrito de forma matricial $(Ax = b)$:

$$
\begin{pmatrix}
-1 & 1\\
1 & 1 \\
\end{pmatrix}
\begin{pmatrix}
x\\
y\\
\end{pmatrix}
=
\begin{pmatrix}
1\\
3\\
\end{pmatrix}
$$

Podemos verla solución de forma gráfica

<img src="ecuaciones.png">

Supongamos que tenemos un sistema de n ecuaciones lineales con n incógnitas. Podemos representar el sistema de forma matricial como:
$$Ax=b$$
Si el sistema tiene una única solución (es compatible determinado), entonces la matriz $A$ es regular (determinante distinto de 0) y, por tanto, existe su matriz inversa $A^{−1}$.
Entonces, podemos multiplicar toda la ecuación por la inversa de $A^{−1}$:
$$A^{-1}\cdot Ax=A^{-1}\cdot b$$
$$x = A^{-1}\cdot b$$
Es decir, si la matriz $A$ es regular, entonces la matriz columna resultante del producto matricial $A^{−1} \cdot b $ contiene la solución del sistema $Ax=b$. 

In [6]:
A = np.array([[-1,1], [1, 1]])
b = np.array([1,3])

#busca como np hace la inversa de una matriz
det_A = np.linalg.det(A)
if det_A != 0:
    adj_A = np.linalg.inv(A).T * det_A
    Ainv = adj_A / det_A

#Cuando tengas la matriz Ainv descomenta las siguientes lineas para comprobar el resultado
print("Ainv * A= ",np.dot(Ainv,A)) # la unidad
print("[x , y]= ",np.dot(Ainv,b))  #solución = 1,2 (ver gráfico)


Ainv * A=  [[1. 0.]
 [0. 1.]]
[x , y]=  [1. 2.]


<hr>
<b><font color='red'>Ejercicio 07</font></b> 

Utilizando la matriz de transición vista en el ejemplo de (Cadenas de Markov), pongamos el caso de una población de 1000 habitantes que en un momento inicial compran 1000 procductos de la marca B, como sería la distribución de compras en la decima compra.

In [7]:
import numpy as np

markov = np.array([[0.6, 0.3], [0.3, 0.5]])

distribucion = np.array([1000, 0])

for i in range(10):
    distribucion = np.dot(distribucion, markov)

print("La distribución en la décima compra sería:")
print(distribucion)


La distribución en la décima compra sería:
[120.3245154 101.9294727]


<hr>
<b><font color='red'>Ejercicio 08</font></b>

En el siguiente juego, 3 niños y 3 niñas juegan a pasarse la pelota, si la probabilidad de pasar la pelota a la derecha o a su izquierda es la misma (1/2), crea la matriz de transición como hemos visto en clase, y obten la probabilidad de que la pelota llegue a 4 en la 3ª ronda si ha empezado en 1. 

sol : 0.25

<img src="pelota.gif">



In [8]:
matriz = np.array([[0, 0.5, 0, 0, 0, 0.5],
                   [0.5, 0, 0.5, 0, 0, 0],
                   [0, 0.5, 0, 0.5, 0, 0],
                   [0, 0, 0.5, 0, 0.5, 0],
                   [0, 0, 0, 0.5, 0, 0.5],
                   [0.5, 0, 0, 0, 0.5, 0]])

print(matriz)

distribucion = np.array([1, 0, 0, 0, 0, 0])

for i in range(3):
    distribucion = np.dot(distribucion, matriz)

print("La probabilidad de que la pelota llegue al 4º niño en la 3º ronda es:")
print(distribucion[3])


[[0.  0.5 0.  0.  0.  0.5]
 [0.5 0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.  0.5 0. ]]
La probabilidad de que la pelota llegue al 4º niño en la 3º ronda es:
0.25


<hr>
<b><font color='red'>Ejercicio 09</font></b>

En 1674 G. Leibnitz da la serie:
$$ \frac{\pi}{4} = 1-\frac{1}{3}+\frac{1}{5}-\frac{1}{7}+\frac{1}{9}+...$$
Es decir que:
$$ \pi = 4-\frac{4}{3}+\frac{4}{5}-\frac{4}{7}+\frac{4}{9}+...$$
Haz la serie hasta el termino $\frac{4}{10000}$, el resultado es 3.14139265359....

In [4]:
aprox = 0
n = 1

for n in range(1,4000,2):
    leibnitz = 1 / n
    if n % 4 == 1:
        aprox += leibnitz
    else:
        aprox -= leibnitz



resultado = 4 * aprox

print(resultado)

3.1410926536210413
